
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = '\xf4\x82\xda\x86\x85a\xc3\x00\x85r &\xac\x91\x0c\xf6'
    
_lr_action_items = {'FROM':([6,7,13,],[9,-9,-10,]),'NAME':([0,4,9,10,15,16,22,23,],[1,7,12,13,18,20,20,25,]),'SEMI':([11,12,14,18,19,21,24,25,],[-5,-11,17,-12,-4,-6,-7,-8,]),'EQUAL':([1,20,],[5,23,]),'COMMA':([6,7,11,12,13,18,19,21,24,25,],[10,-9,15,-11,-10,-12,22,-6,-7,-8,]),'WHERE':([11,12,18,],[16,-11,-12,]),'SELECT':([0,5,],[4,4,]),'$end':([2,3,8,17,],[0,-2,-1,-3,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'condition_list':([16,],[19,]),'attrlist':([4,],[6,]),'opt_where_clause':([11,],[14,]),'assign_statement':([0,],[2,]),'select_statement':([0,5,],[3,8,]),'tablist':([9,],[11,]),'condition':([16,22,],[21,24,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> assign_statement","S'",1,None,None,None),
  ('assign_statement -> NAME EQUAL select_statement','assign_statement',3,'p_statement_assign','C:/Users/yluo/PycharmProjects/cmddb/ssqlparser.py',62),
  ('assign_statement -> select_statement','assign_statement',1,'p_statement_assign','C:/Users/yluo/PycharmProjects/cmddb/ssqlparser.py',63),
  ('select_statement -> SELECT attrlist FROM tablist opt_where_clause SEMI','select_statement',6,'p_statement_select','C:/Users/yluo/PycharmProjects/cmddb/ssqlparser.py',72),
  ('opt_where_clause -> WHERE condition_list','opt_where_clause',2,'p_statement_opt_where','C:/Users/yluo/PycharmProjects/cmddb/ssqlparser.py',78),
  ('opt_where_clause -> <empty>','opt_where_clause',0,'p_statement_opt_where','C:/Users/yluo/PycharmProjects/cmddb/ssqlparser.py',79),
  ('condition_list -> condition','condition_list',1,'p_statement_condition_list','C:/Users/yluo/PycharmProjects/cmddb/ssqlparser.py',88),
  ('condition_list -> condition_list COMMA condition','condition_list',3,'p_statement_condition_list','C:/Users/yluo/PycharmProjects/cmddb/ssqlparser.py',89),
  ('condition -> NAME EQUAL NAME','condition',3,'p_statement_condition','C:/Users/yluo/PycharmProjects/cmddb/ssqlparser.py',98),
  ('attrlist -> NAME','attrlist',1,'p_statement_attr','C:/Users/yluo/PycharmProjects/cmddb/ssqlparser.py',104),
  ('attrlist -> attrlist COMMA NAME','attrlist',3,'p_statement_attr','C:/Users/yluo/PycharmProjects/cmddb/ssqlparser.py',105),
  ('tablist -> NAME','tablist',1,'p_statement_tablist','C:/Users/yluo/PycharmProjects/cmddb/ssqlparser.py',115),
  ('tablist -> tablist COMMA NAME','tablist',3,'p_statement_tablist','C:/Users/yluo/PycharmProjects/cmddb/ssqlparser.py',116),
]
